osx_image: xcode8
language: objective-c
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - gem update --system
  - rvm osx-ssl-certs update all
  - gem install xcpretty -N
script:
  - set -o pipefail
  - brew update
  - brew install carthage
  - ./checkout.sh
  - rm -rf build
  - xcodebuild -project Client.xcodeproj -scheme "Firefox" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO -derivedDataPath build clean test | xcpretty -c

