# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Continous deployment for Cliqz iOS"
	
  # Configuring Sentry DSN
  sh("cd .. && plutil -replace SentryDSN -string $SentryDSN Client/Info.plist")
  	
  # Building ReactNative Entension
  sh("cd .. && npm run bundle")
  
  
  lane :beta do    

    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      git_branch: "browser-ios",
      readonly: true,
      verbose: true
    )

    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Client.xcodeproj"
    )

    build_app(
      workspace: "Client.xcworkspace",
      clean: "true",
      scheme: "Firefox",
      export_options: {
        provisioningProfiles: { 
          "cliqz.ios.CliqzBeta" => "match AppStore cliqz.ios.CliqzBeta",
          "cliqz.ios.CliqzBeta.Cliqz" => "match AppStore *",
          "cliqz.ios.CliqzBeta.SendTo" => "match AppStore *", 
          "cliqz.ios.CliqzBeta.ShareTo" => "match AppStore *", 
          "cliqz.ios.CliqzBeta.Today" => "match AppStore *", 
          "cliqz.ios.CliqzBeta.ViewLater" => "match AppStore *"
        }
      }
    )

  	upload_to_testflight(
  		changelog: "Nightly build",
  		demo_account_required: "false",
      skip_waiting_for_build_processing: "true"
  	)
  end

  lane :release do
    
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      git_branch: "browser-ios",
      readonly: true,
      verbose: true
    )

    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Client.xcodeproj"
    )

    build_app(
      workspace: "Client.xcworkspace",
      clean: "true",
      scheme: "Firefox",
      export_options: {
        provisioningProfiles: { 
          "com.cliqz" => "match AppStore com.cliqz",
          "com.cliqz.cliqzshare" => "match AppStore *",
          "com.cliqz.SendTo" => "match AppStore *", 
          "com.cliqz.ShareTo" => "match AppStore *", 
          "com.cliqz.Today" => "match AppStore *", 
          "com.cliqz.ViewLater" => "match AppStore *"
        }
      }
    )

    upload_to_testflight(
      changelog: "AppleStore Release",
      demo_account_required: "false",
      skip_waiting_for_build_processing: "true"
    )
  end

end
